# Generated by Django 2.1.7 on 2019-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
