# Generated by Django 2.1.7 on 2019-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_profile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Shop'),
        ),
    ]
