# Generated by Django 2.1.7 on 2019-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shop',
            field=models.ManyToManyField(to='shop.Shop'),
        ),
    ]
